version: '3'
services:
  nginx:
    # image: nginx:latest
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      # - ./src/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php
    # app:
    #   build: ./docker-php
    #   depends_on:
    #       - db
    #   links:
    #       - db
    #   volumes:
    #       - ./:/var/www/html

  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: webapp
      MYSQL_USER: akira
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db


# version: '2'
# services:
#   nginx:
#     image: nginx:latest
#     ports:
#       - 8080:80
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#       - ./src:/var/www/html
#     depends_on:
#       - php

#   php:
#     build: ./php
#     volumes:
#       - ./src:/var/www/html
#       - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
#     depends_on:
#       - db

#   db:
#     image: mysql:latest
#     ports:
#       - 3306:3306  
#     volumes:
#       - ./mysql/data:/var/lib/mysql
#       - ./mysql/sql:/docker-entrypoint-initdb.d
#       - ./mysql/my.cnf:/etc/mysql/conf.d
#     environment:
#       MYSQL_DATABASE: db_connect
#       MYSQL_USER: akira
#       MYSQL_PASSWORD: password
#       MYSQL_ROOT_PASSWORD: secret 

      


#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:latest
#     ports:
#       - 8888:80
#     depends_on:
#       - db