version: '2'
services:
  nginx:
    # image: nginx:latest
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./src/usr/share/nginx/html
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./www/html:/var/www/html
    # depends_on:
    #   - php
    app:
      build: ./docker-php
      depends_on:
          - db
      links:
          - db
      volumes:
          - ./:/var/www/html


  # php:
  #   build: ./php
  #   volumes:
  #     - ./www/html:/var/www/html
  #   depends_on:
  #     - db

  # db:
  #   platform: linux/amd64
  #   image: mysql:5.7
  #   ports:
  #     - 13306:3306
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: secret

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   ports:
  #     - 8888:80
  #   depends_on:
  #     - db